### ISSUE TITLE
Using embeds

### ISSUE THREAD

**Issue by moneymc** [godly-devotion/MochiDiffusion#101]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Hi

Is it possible to use embeds in Mochi Diffusion? 
I mean all this cool things: https://huggingface.co/spaces/sd-concepts-library/stable-diffusion-conceptualizer

### Why do you think this should be added?

It's very important thing.

**Comment by godly-devotion** [comment]
As far as I know, Stable Diffusion Core ML does not currently support embeds.
