### ISSUE TITLE
The resulting images are just noise (Intel processor)

### ISSUE THREAD

**Issue by Vitkarus** [godly-devotion/MochiDiffusion#105]
### Running Latest Version

- [X] I am running the latest version

### Processor

Intel

### Intel processor

i5 10600 and RX 6600 XT 8Gb

### Memory

16GB

### What happened?

Original models from Hugging Face only produce noise, but split_einsum ones works just fine, what could be the problem?
<img width="1448" alt="Pic" src="https://user-images.githubusercontent.com/68278744/213922996-f67b0ca4-6328-49f5-8c76-6ae960ef4fe5.png">

**Comment by Vitkarus** [comment]
I tried other models and apparently I made a mistake the first time, still getting broken pictures, but it does not depend on whether this model is original or split_einsum, but on the resolution. 512x512 works fine, but at 512x768 I get noise

**Comment by irmantus** [comment]
Same issue. Model Dreamlike Diffusion 512x768

<img width="645" alt="image" src="https://user-images.githubusercontent.com/37515045/215094935-bd3c7440-c078-4b6e-bc18-e78a9f1f1dba.png">

**Comment by godly-devotion** [comment]
@irmantus Does your Mac also use Intel processor?

**Comment by irmantus** [comment]
Yes, iMac 2020 with Intel.

**Comment by godly-devotion** [comment]
So I guess either ‘original’ versions of the models aren’t fully supported on Intel or the way we are converting them doesn’t work for it.

**Comment by Vitkarus** [comment]
Hm, maybe that problem should be pushed to Apple's main SD repo then? I have also read issues on ml-stable-diffusion, and as I get, there is no way that we can expect changeble resolution with CoreML similar to Automatic111 Web UI and similar tools? Even if they are more versitale, but I get almost a double increase in speed with Mochi (about 1.7s per iteration on Automatic vs iteration in less then a second) and much less memory usage, which is really nice

**Comment by godly-devotion** [comment]
Well it would still be nice for `original` models to be able to run properly on Intel Macs as only `original` models can be created with image sizes other than 512x512.

**Comment by irmantus** [comment]
I tested [epicDiffusion](https://huggingface.co/coreml/coreml-epic-diffusion) that afaik is 512x512 and it still generated noise. So maybe its not resolution related issue. 

<img width="239" alt="image" src="https://user-images.githubusercontent.com/37515045/216361577-d08215bc-4fa7-4e05-ad1f-cb442a03b8b1.png">
