### ISSUE TITLE
Save Settings with each new batch

### ISSUE THREAD

**Issue by Quick-Eyed-Sky** [godly-devotion/MochiDiffusion#106]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I wish to have the possibility to save a setting.txt with each picture saved (even with "save all"). I know that the filename is the prompt, but it's of course incomplete. Like with a colab, in a way.

### Why do you think this should be added?

To find the exact settings, prompts, negative prompt, seed, and all, next to each picture.

**Comment by godly-devotion** [comment]
In the meantime the pictures have exif data so you can use a tool such as ‘exiftool’ to see the prompt info.

**Comment by Quick-Eyed-Sky** [comment]
> Le 22 janv. 2023 à 19:29, Joshua Park ***@***.***> a écrit :
> 
> 
> In the meantime the pictures have exif data so you can use a tool such as ‘exiftool’ to see the prompt info.
> 

Perfect. Command-I on my Mac and I get everything. Thanks!

JP

**Comment by godly-devotion** [comment]
Since it’s easy to see the image’s generated settings I will close this issue for now.
