### ISSUE TITLE
Feature Request: More Samplers

### ISSUE THREAD

**Issue by ancker010** [godly-devotion/MochiDiffusion#113]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Please add support for additional samplers, such as "euler a" etc.

### Why do you think this should be added?

Different samplers work better for different types of prompts and expected outputs.

**Comment by godly-devotion** [comment]
This is something that needs to be done upstream, see https://github.com/apple/ml-stable-diffusion/issues/86
