### ISSUE TITLE
Focus locked to prompt boxes

### ISSUE THREAD

**Issue by Myridium** [godly-devotion/MochiDiffusion#114]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

Focus remains on prompt boxes, even after clicking in the image gallery area. Arrow keys do not move between images. Cannot press spacebar to quickview, either.

**Comment by godly-devotion** [comment]
See under Image menu for Gallery keyboard shortcuts.

**Comment by Myridium** [comment]
Okay, good to know. However I think this is still poor user design. It is standard practice to bring focus into the area where the user clicks. Good UX practice should adhere to common conventions. After I click on an image, it puts a highlight border around that image. Selectable items are arranged in a grid, and the coloured highlight suggests that the window focus is on this grid. Therefore I expect to be able to use the arrow keys to navigate the items in that grid.

**Comment by godly-devotion** [comment]
I am open to pull request that fixes this behavior. I personally haven't figured out how to remove focus from the text input controls yet thus requiring the Cmd modifier key.
