### ISSUE TITLE
Wiki help: converting safetensor/ckpt to coreML; conda activate st_gui

### ISSUE THREAD

**Issue by evliu** [godly-devotion/MochiDiffusion#119]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

when running command
`conda activate st_gui`
it results in 
`EnvironmentNameNotFound: Could not find conda environment: st_gui`

New to this so would love some guidance

### Why do you think this should be added?

how do I add the st_gui env? new to python. thanks!!

**Comment by godly-devotion** [comment]
Please ask questions on [Discord](https://discord.gg/x2kartzxGv). Issues are for bugs and requests only.
