### ISSUE TITLE
Token count

### ISSUE THREAD

**Issue by Draxredd** [godly-devotion/MochiDiffusion#121]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

having a token count for prompts. either a counter, a hard limit in field or some color coding when over the limit

### Why do you think this should be added?

Core ML model prompts are limited to 75 tokens.

**Comment by godly-devotion** [comment]
So the token≈word isn't correct. I can see the text being truncated in Xcode output but parts of words are getting truncated if it goes over the "token" length. I've tried looking at [webui's implementation of their token counter](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5034f7d7597685aaa4779296983be0f49f4f991f) but the code is messy and isn't very straight forward. I'll be open to a PR but I can't figure out exactly what a token is.

**Comment by godly-devotion** [comment]
A helpful rule of thumb is that one token generally corresponds to ~4 characters of text for common English text. This translates to roughly ¾ of a word (so 100 tokens ~= 75 words).

**Comment by takoyaro** [comment]
From the same source, 
> If you need a programmatic interface for tokenizing text, check out the [transformers](https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2TokenizerFast) package for python or the [gpt-3-encoder](https://www.npmjs.com/package/gpt-3-encoder) package for node.js.

The `gpt-3-encoder` package provides a [python](https://github.com/latitudegames/GPT-3-Encoder/blob/master/encoder.py) implementation as well as a [javascript](https://github.com/latitudegames/GPT-3-Encoder/blob/master/Encoder.js) one.

Both of which give me a more accurate token count than what Mochi provides me with currently. Unfortunately I have never wrote a single line of Swift so I have no idea how I would implement this but I thought I'd leave the info out there.

**Comment by godly-devotion** [comment]
> The `gpt-3-encoder` package provides a [python](https://github.com/latitudegames/GPT-3-Encoder/blob/master/encoder.py) implementation as well as a [javascript](https://github.com/latitudegames/GPT-3-Encoder/blob/master/Encoder.js) one.
> 
> Both of which give me a more accurate token count than what Mochi provides me with currently. Unfortunately I have never wrote a single line of Swift so I have no idea how I would implement this but I thought I'd leave the info out there.

Token counts differ based on the model's vocab list. Also after I made the initial commit for the naive token counter, @CarterLombardi improved it by actually calculating the real token count (commit: https://github.com/godly-devotion/MochiDiffusion/commit/034bbe773f355ab829999b10a2a8d704de5451d6)
