### ISSUE TITLE
DPM Solver ++ implementation not correct?

### ISSUE THREAD

**Issue by Myridium** [godly-devotion/MochiDiffusion#122]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

I found that the "DPM-Solver ++" scheduler did not produce the same results (with a given seed) as any one of the following schedulers from Automatic1111's webui:
 - DPM++ 2S a
 - DPM++ 2M
 - DPM++ SDE
 - DPM++ 2S a Karras
 - DPM++ 2M Karras
 - DPM++ SDE Karras

I think that Automatic1111's implementation supposedly matches the canonical implementation.
So, I think that the Mochi Diffusion implementation is probably incorrect. It does not say which DPM++ solver it is exactly. Can you be more specific as to exactly which DPM++ algorithm it is?

It is important to use the correct implementation, so that prompts and configurations are portable across different applications.

**Comment by godly-devotion** [comment]
See https://github.com/apple/ml-stable-diffusion/pull/59. Also you will never get exactly the same images even with the same seed and prompt. Changing even just changing the compute unit will slightly change the image as well (https://github.com/apple/ml-stable-diffusion/pull/59)

**Comment by Myridium** [comment]
> See [apple/ml-stable-diffusion#59](https://github.com/apple/ml-stable-diffusion/pull/59). Also you will never get exactly the same images even with the same seed and prompt between Core ML and diffusers models. Changing even just the compute unit will slightly change the image as well (https://github.com/apple/ml-stable-diffusion#-results-with-different-compute-units)

The differences I'm talking about are black and white. Just totally different images. Are you sure this is expected?
