### ISSUE TITLE
Rest Api Server like Automatic1111

### ISSUE THREAD

**Issue by RageshAntony** [godly-devotion/MochiDiffusion#123]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

In Automatic1111 Web UI, they provide an REST API server along with it, so one could able to generate images by calling the API

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

### Why do you think this should be added?

So people able to automate things instead of manually entering each prompt

**Comment by godly-devotion** [comment]
This is mostly a user interactive app so it’ll probably won’t be implemented. You can however use the official CLI to automate generation. See https://github.com/apple/ml-stable-diffusion#example-cli-usage

**Comment by RageshAntony** [comment]
@godly-devotion 
Okay thanks.

I suggest an inbuilt ckpt => coreml conversion tool within the app. Is that possible ?

**Comment by RageshAntony** [comment]
@godly-devotion 
Also, I cloned this repo. I am new to xcode dev. (Myself an android dev)

How to run without profiles and certificates in "My Mac" target in development mode ?
