### ISSUE TITLE
Inkpunk-Diffusion_original_compiled.zip can't decompressed

### ISSUE THREAD

**Issue by h4rk8s** [godly-devotion/MochiDiffusion#124]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Max (or later)

### Memory

64GB (or higher)

### What happened?

from https://huggingface.co/coreml download model , but can't decompressed.

**Comment by godly-devotion** [comment]
Looks like that file got corrupted somehow during upload. I've deleted the file. You should download the `split_einsum` version instead.
