### ISSUE TITLE
Hard crash "BUG IN CLIENT OF LIBDISPATCH: Unbalanced call to dispatch_group_leave()"

### ISSUE THREAD

**Issue by beatrixwillius** [godly-devotion/MochiDiffusion#130]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

8GB

### What happened?

Got a crash in my first test. I downloaded the model "stable-diffusion-v2.1-base_original_compiled" and moved it to the documents folder. Then I restarted Mochi and entered a prompt. After a couple of minutes I noticed that the app had crashed.

I can't find anything related to "Problem Details and System Configuration" in the app.
[Mochi Diffusion-2023-02-02-150931.ips.zip](https://github.com/godly-devotion/MochiDiffusion/files/10570013/Mochi.Diffusion-2023-02-02-150931.ips.zip)

**Comment by godly-devotion** [comment]
Did you run the generation with `Use Neural Engine` or `Use GPU`?

**Comment by beatrixwillius** [comment]
I used "CPU + Neural Engine" which was the default value.

**Comment by beatrixwillius** [comment]
I'm probably odd that I expect an app to disallow combinations of settings that make an app crash. But I'm just an developer.

**Comment by godly-devotion** [comment]
There is no way to tell if a model is `original` or `split_einsum` after it has been converted.

**Comment by angeenes** [comment]
Just a small idea, maybe reading the folder name ( which has the type of model ) could help to use a condition to use one or other option. It’s probably not a long term solution… but could give an hint to confirm the choice.

**Comment by godly-devotion** [comment]
I’ve thought about that but I don’t want users relying on a safeguard that only works sometimes. Honestly most people have no issues as they read the short message in pop up at minimum.

**Comment by angeenes** [comment]
> safeguard that only works sometimes

I totally agree, thanks for your reply.
