### ISSUE TITLE
Regression in "Convert ckpt → diffusers" instruction

### ISSUE THREAD

**Issue by ikolomiets** [godly-devotion/MochiDiffusion#156]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Max (or later)

### Memory

64GB (or higher)

### What happened?

I noticed that [conversion instruction](https://github.com/godly-devotion/MochiDiffusion/wiki/How-to-convert-ckpt-or-safetensors-files-to-Core-ML) step where you have to download from the [huggingface/diffusers](https://github.com/huggingface/diffusers/) Github repo and run the  [convert_original_stable_diffusion_to_diffusers.py](https://github.com/huggingface/diffusers/raw/main/scripts/convert_original_stable_diffusion_to_diffusers.py) script no longer works (the old version of this script does work). Attempt to run latest version results in this error:

```
% python convert_original_stable_diffusion_to_diffusers.py                                                   
Traceback (most recent call last):
  File "convert_original_stable_diffusion_to_diffusers.py", line 19, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_pipeline_from_original_stable_diffusion_ckpt
ModuleNotFoundError: No module named 'diffusers.pipelines.stable_diffusion.convert_from_ckpt'
```

Please advise.

**Comment by Zabriskije** [comment]
I've tried right now and it's working.
Is the conda `coreml_stable_diffusion` environment active when you run `python ./convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./CHECKPOINT_FILE.ckpt --device cpu --extract_ema --dump_path ./diffusers_model`, right?
If so, I think I had the same issue once and deleting + downloading again the `coreml_stable_diffusion` conda envs did the trick.

**Comment by MDMAchine** [comment]
Looks like you dont have the module-ised "convert_from_ckpt.py"
while in the environment try running `pip install diffusers`
Then check in lib>python3.10>site-packages>diffusers>pipelines>stable_diffusion>convert_from_ckpt.py And make sure its there, if not you can delete the entire diffusers folder and re-install (above).
One this update happens there is some issues with conversions on 2.1 models. [See here on discord](https://discord.com/channels/1068185566782423092/1068187870537449532/1074320220828733503)

**Comment by ikolomiets** [comment]
Thank you! Deleting stale `envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers` directory and re-installing it with `pip install diffusers` fixed the issue!

**Comment by ikolomiets** [comment]
Thank you! Deleting stale envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers directory and re-installing it with pip install diffusers fixed the issue!

**Comment by kaiqiangh** [comment]
I tried the approach mentioned above (delete diffuser and re-install it), but it did not work - show the same error. Any suggestions?
