### ISSUE TITLE
Support token weights

### ISSUE THREAD

**Issue by GaidamakUA** [godly-devotion/MochiDiffusion#166]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I want to be able to set weight for a specific words, like I do in Midjourney or others.

### Why do you think this should be added?

This is an important feature that gives better artistic control over generation.

**Comment by godly-devotion** [comment]
This is something that will need to be implemented by [Apple’s Core ML library](https://github.com/apple/ml-stable-diffusion) itself.
