### ISSUE TITLE
Whether Lora can be used in this software

### ISSUE THREAD

**Issue by soyi** [godly-devotion/MochiDiffusion#169]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Use lora to improve the quality of pictures

### Why do you think this should be added?

Lora is necessary

**Comment by godly-devotion** [comment]
I have absolutely no idea what lora is.

**Comment by vzsg** [comment]
I believe it's [LoRa}(https://huggingface.co/blog/lora) (another explanation page [here](https://replicate.com/blog/lora-faster-fine-tuning-of-stable-diffusion)), an algorithm to train/enhance models for specific styles. Very out of scope for the app IMHO.

**Comment by godly-devotion** [comment]
I see, yeah this is out of scope for this project, at least for now.
