### ISSUE TITLE
How do I run it, please? 

### ISSUE THREAD

**Issue by 623005116** [godly-devotion/MochiDiffusion#174]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

How do I run it, please? I'm sorry guys, I'm not particularly familiar with programming. I have downloaded the project, but I don't know how to run it.

### Why do you think this should be added?

It would be great if you could add a sentence in the description file on how to run the application, especially for someone like me who doesn't know anything about programming. Thank you all very much.

**Comment by godly-devotion** [comment]
Questions should go into our [Discord server](https://discord.gg/x2kartzxGv).

**Comment by 623005116** [comment]
您好，我已收到您的邮件，将尽快给您回复。祝工作顺利！
