### ISSUE TITLE
Visual bug when selecting `Apply` from settings panel

### ISSUE THREAD

**Issue by Zabriskije** [godly-devotion/MochiDiffusion#178]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

8GB

### What happened?

A visual bug happens when you click `Apply` from the settings panel (also with no changes made).
It doesn't happen when you deactivate one or more options in the `General` tab.

https://user-images.githubusercontent.com/101254295/221417627-f1dad96d-56d2-4fbe-b2a5-d870251931cc.mov

**Comment by vzsg** [comment]
This is definitely happening. When the Apply button is pressed, all images are removed from the gallery and added back asynchronously as a second step, animating this (rather unnecessary) transition.
