### ISSUE TITLE
Add a Quick Look to view images in the app via the spacebar

### ISSUE THREAD

**Issue by RozenPS** [godly-devotion/MochiDiffusion#185]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Open the Quick Look preview window with the selected picture by pressing the spacebar inside the application

### Why do you think this should be added?

I think it would be convenient to open the resulting images on a larger scale instantly and without going to the Finder.
Thank you for your work!

**Comment by godly-devotion** [comment]
This is already possible via Image > Quick Look (Command+L). I can't use spacebar because it sometimes interferes with the text inputs.

**Comment by RozenPS** [comment]
Ok, Command+L is good enough
