### ISSUE TITLE
Prompt are not limited to 75 characters

### ISSUE THREAD

**Issue by ishowshao** [godly-devotion/MochiDiffusion#187]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Prompt are not limited to 75 characters

### Why do you think this should be added?

we need more

**Comment by Gomeo** [comment]
I believe the 75 word limitation is from Apple's SD Core ML library

**Comment by vzsg** [comment]
I believe it is a bit more complicated: the models themselves have a token limit, which is commonly 75 for older models. Apple's library has the [means of asking the model](https://github.com/apple/ml-stable-diffusion/blob/main/swift/StableDiffusion/pipeline/TextEncoder.swift#L48-L49) about the limit, which is not accessible from our side. If Apple exposed the limit, or we loaded a second copy of the encoder model ourselves, it could be made dynamic.

**Comment by Gomeo** [comment]
Thanks for looking into it mate. I noticed you're still quite active on development! Appreciate your work and effort.
