### ISSUE TITLE
有没有可能加入lora的支持呢？

### ISSUE THREAD

**Issue by sirlioniva** [godly-devotion/MochiDiffusion#188]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

加入原版stable diffusion的lora插件功能可行吗？

### Why do you think this should be added?

metal速度比cpu gpu跑快了6-7倍，希望能加入插件完善

**Comment by godly-devotion** [comment]
Duplicate of #169.
