### ISSUE TITLE
Time to generate should show up either in the app UI, the image data, or a log you could check out

### ISSUE THREAD

**Issue by jasontitus** [godly-devotion/MochiDiffusion#189]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

In order to tune image creation parameters it is very useful to know how long it takes with each one (ANE & GPU?  CPU?  25 steps?  50 steps? - lots to tune)

### Why do you think this should be added?

It will help users to make choices on some of the many parameters.

**Comment by jrittvo** [comment]
This is sort of resolved by the time remaining estimate in the image generation preview display.  Not quite the same as saving time-to-generate in the completed image metadata, but a start.
