### ISSUE TITLE
Can you add a comparison of different configurations

### ISSUE THREAD

**Issue by answer42n** [godly-devotion/MochiDiffusion#190]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Provide a running comparison similar to Intel processor m1 m1pro m1max m2 m2pro m2max

### Why do you think this should be added?

Provide expectations and references for users

**Comment by godly-devotion** [comment]
Someone has already made a comparison chart available here: https://github.com/huggingface/swift-coreml-diffusers/issues/31
