### ISSUE TITLE
Non-destructive removal of imported images

### ISSUE THREAD

**Issue by MDMAchine** [godly-devotion/MochiDiffusion#191]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

When I import images later on to resize, for example. There is no clear indication that removing them after modification will send them to trash. The only way to clear imported images non-destructively is to close/open the app or change the low memory setting.

### Why do you think this should be added?

It would be nice to quickly remove the imported images without having to change memory settings or close and reopen the app. Also it would be nice to have the option to save the orignal smaller image copy during the resize operation (especially if later we have other upscale sampler options).

**Comment by vzsg** [comment]
Definitely agree on having a setting to preserve the original, sometimes it worsens the image quality and I have to regenerate from the same parameters.

And IMHO the other point also makes sense: if saving to the filesystem is enabled, removing from the gallery and destructively deleting from the filesystem should be two separate actions, like it is in many different apps.
