### ISSUE TITLE
The selected model does not support setting a starting image error message 

### ISSUE THREAD

**Issue by highfiiv** [godly-devotion/MochiDiffusion#192]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

With the amazing new img2img feature I'm unclear which models can use the pipeline. Instead we see a genertic error message informing us that this model does not support the pipeline.

Is this in error? and what models do support the new img2img feature?

### Why do you think this should be added?

Either support for more models or a list of img2img capable models.

*incredible work here.

**Comment by Zabriskije** [comment]
It's specified in the v3 release notes: if your model has a `VAEEncoder.mlmodelc` file/folder, it can do img2img.
On our [Hugging Face repo](https://huggingface.co/coreml), the models that do not support img2img are marked with the `no-i2i` suffix, as stated in the org card.
We're planning to convert again all the models that do not to support img2img, but it will take a bit of time.
