### ISSUE TITLE
Subfolder in folder model causes CTD

### ISSUE THREAD

**Issue by Draxredd** [godly-devotion/MochiDiffusion#193]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

creatred a "noi2i" folder inside the model folder to organize things. "noi2i" appears in the model list, selecting this crashes mochi diffusion.

**Comment by jrittvo** [comment]
I don't think this is a bug, really.  The app instructions explain how models need to be stored.  But the ability to use nested folders would be a nice enhancement.

**Comment by Draxredd** [comment]
I know I'm doing something not supposed to be done, yet a CTD is definitely a bug.

**Comment by vzsg** [comment]
Probably the same issue as #165 underneath.
