### ISSUE TITLE
Inpainting / outpainting

### ISSUE THREAD

**Issue by saiedg** [godly-devotion/MochiDiffusion#197]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Hi! Would be great if this had inpainting AND outpainting. Is this something currently being worked on?

### Why do you think this should be added?

Open sourcing 2 powerful features

**Comment by aajank** [comment]
true inpainting would be cool

**Comment by godly-devotion** [comment]
Requires implementation from Apple's library here: https://github.com/apple/ml-stable-diffusion
