### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Quick-Eyed-Sky** [godly-devotion/MochiDiffusion#198]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

2.5 and 3.0 both crash immediately after start. I "tries" to load something for 0,1 sec then crashes. I emptied the model folder but it did not solve the problem.
I got: 

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000102511930

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1722]

### Crash Log

```shell
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000102511930

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1722]
```

**Comment by BinReco** [comment]
also crash

**Comment by vzsg** [comment]
Try removing the preferences file of the application, e.g. with the following command in Terminal:

```sh
rm ~/Library/Preferences/com.joshua-park.Mochi-Diffusion.plist
```

This will give you a completely fresh start.

**Comment by gaoyang07** [comment]
I solved the exact same bug by realizing that I had not generated the required `.mlmodelc` files using Xcode...

**Comment by godly-devotion** [comment]
Are you still having this issue?
