### ISSUE TITLE
PLS add feature: controlnet support

### ISSUE THREAD

**Issue by crazyshitass** [godly-devotion/MochiDiffusion#199]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Hope add support for controlnet.

### Why do you think this should be added?

A cool feature

**Comment by godly-devotion** [comment]
Needs to be implemented in Apple's library here: https://github.com/apple/ml-stable-diffusion

**Comment by zwpaper** [comment]
now that apple library supported controlnet, https://github.com/apple/ml-stable-diffusion/tree/5d2744e38297b01662b8bdfb41e899ac98036d8b#-results-with-controlnet, suppose we could support it too?

@godly-devotion can you help to confirm whether MochiDiffusion can run controlnet and how it can be run?
