### ISSUE TITLE
does not restore generated images saved with jpeg

### ISSUE THREAD

**Issue by seanmpuckett** [godly-devotion/MochiDiffusion#201]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Max (or later)

### Memory

64GB (or higher)

### What happened?

change settings to autosave/restore images type **jpeg**
generate an image
quit the app
relaunch the app
the just generated image is **not restored**

(heic and png images are successfully restored)

**Comment by vzsg** [comment]
Interestingly enough, only the automatic import is affected. Manually importing the same JPEG file works.
This suggests that it should be easily fixable 🙂
