### ISSUE TITLE
Control Net

### ISSUE THREAD

**Issue by MDMAchine** [godly-devotion/MochiDiffusion#204]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

See if it can be implemented.

### Why do you think this should be added?

Looks like Guernika got control net working for coreml. 

https://github.com/apple/ml-stable-diffusion/issues/131#issuecomment-1472936314

https://discord.com/channels/1068185566782423092/1068187960350085140/1086608907004297216

**Comment by jrittvo** [comment]
A pull request was just dropped at apple/ml-stable-diffusion for this.  Covers model conversion, the inference pipeline, and implementation in swift:  https://github.com/apple/ml-stable-diffusion/pull/153

**Comment by jrittvo** [comment]
Apple merged the ControlNet stuff into `apple/ml-stable-diffusion` a few days ago.  I've been playing with converting models and running them through a Swift command line interface.  I'm slowly putting my ControlNet stuff on a page at Hugging Face.  Right now, there is a ControlNet capable version of the SD-1.5 original 512x512 model and Canny and Scribble ControlNet models.  I'm staying away from doing split_einsum models for now, but there are notes covering that as well.  I have more models and more notes that I will add tomorrow and over the weekend.  So far there is a note on setting up a Conda environment and another walking through converting full models for ControlNet use and also converting the individual ControlNet models themselves.  I will get the notes on the Swift-CoreML command line pipeline finished and uploaded tomorrow.  Using them in a CLI interface is much simpler than doing the conversions.  Here is the link:  https://huggingface.co/jrrjrr/CoreML-Models-For-ControlNet

**Comment by Exynos-8890** [comment]
So I can't wait to use ControlNet plugin in Mochi!!

**Comment by stuartjmoore** [comment]
Opened a PR to expose ControlNet in #245.
