### ISSUE TITLE
increase steps limit

### ISSUE THREAD

**Issue by norflin321** [godly-devotion/MochiDiffusion#206]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

i think it would be better to limit steps to 150 (and not 50)

### Why do you think this should be added?

it will allow to produce better images, https://github.com/huggingface/swift-coreml-diffusers has 150 limit

**Comment by ikolomiets** [comment]
from my experience steps in the range 50-80 keep producing hight quality variants with models that were fine-tuned with Dreambooth.

**Comment by godly-devotion** [comment]
Dreambooth and Core ML produce different results based on what sampler is used. Stable Diffusion Core ML currently supports DPM Solver++ (default) and PNDM. DPM Solver++ can resolve an image with lower amount of steps than other samplers.

**Comment by ten0hira** [comment]
any solution?

**Comment by tjkirch** [comment]
I also often get better results beyond 50 steps.  It helps reduce wonkiness in the generated image if more specific details were requested.  Mochi Diffusion already generates images so quickly that I'd really like to wait a few more minutes for even a chance at a better result - as it is, I have no option.
