### ISSUE TITLE
Add support for inpainting 

### ISSUE THREAD

**Issue by aajank** [godly-devotion/MochiDiffusion#207]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I am new to this. Is inpainting supported in mochi diffusion.If so how.

### Why do you think this should be added?

Inpainting

**Comment by vzsg** [comment]
It's not supported now, as things like that are expected to come from apple/ml-stable-diffusion (judging from the opened issue over there, you've found it 🙂). There's not much Mochi could do about it until then.
