### ISSUE TITLE
Possible Fix For image2image 512x768 and 768x512

### ISSUE THREAD

**Issue by jrittvo** [godly-devotion/MochiDiffusion#208]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Someone appears to have found that the width and height parameters are transposed between the t2i and i2i parts of the Automatic1111 pipeline on MacOS.  Perhaps this same issue is the root of why Mochi has only been able to implement i2i at 512x512.  Please look at this thread section and decide if this is worth investigating.  https://github.com/apple/ml-stable-diffusion/issues/143#issuecomment-1487612611

### Why do you think this should be added?

This was something you hoped to include in the i2i implementation, I believe.

-------------------------------------------------------------------

![Screenshot](https://user-images.githubusercontent.com/114269461/228406178-11cac882-7ba1-4fd7-b556-29884a115cc3.jpg)

**Comment by jrittvo** [comment]
i just noticed another thread that is pointing to the same  "transposing" of h and w somewhere in the pipeline as the cause for image to image not seeming to work except at 512x512 .  https://github.com/apple/ml-stable-diffusion/issues/140  If Apple continues to ignore this issue, couldn't Mochi Diffusion step in and internally "un-transpose" the dimension arguments to correct the error?  It already checks to see if the starting image is 512x512.  If it finds the starting image to be say 512x768, it could try reporting the size as 768x512 at points were the code is reversing h and w erroneously.  The two opposite "wrongs" might make it "right". Ugly, but it could be a work-around until Apple issues a real fix.

**Comment by vzsg** [comment]
Such a crazy idea! And I think it will be fruitful. I didn't look into how to transpose the image from Mochi yet or if it's necessary. Instead, I edited [one line in Apple's source](https://github.com/apple/ml-stable-diffusion/blob/7f65e1c84bb8b494b10169c7ae6232bf081a04f8/swift/StableDiffusion/pipeline/CGImage%2BvImage.swift#L114), flipping the width and height parameters, and it started working. (Of course, after removing the 512x512 limit.)

|Input image||Output image|
|-|-|-|
|![beatiful blonde girl sitting at a table outdoors in front of a restaur 3 72969969](https://user-images.githubusercontent.com/1783465/234546242-6ba3707f-a782-4b27-bf0d-a0f111cac9ea.png)| ➡️ |![beatiful blonde girl sitting at a table outdoors in front of a restaur 4 1329554411](https://user-images.githubusercontent.com/1783465/234546270-3edae5c6-0765-4da1-a748-881885e8a985.png)|

---

Considering that for square images the two numbers are equal, and the flipped numbers work for other sizes, maybe this is all that needs to be fixed (in that repo).

**Comment by vzsg** [comment]
We'll see what happens.

**Comment by jrittvo** [comment]
Thank you! They have accepted 2 merge requests in the past 2 days, and they fixed another simple error in their code from an issue I raised yesterday, so I’m hopeful.

**Comment by jrittvo** [comment]
I just thought of a possible software regression that this change might trigger.  I think it is something you could check quickly, and I will try to check it in my Swift CLI pipeline later today.  Apple added in support for ControlNet to ml-stable-diffusion last week.  In trying it out, I noticed that it was not converting models of any size EXCEPT 512x512.  I reported the bug and it was fixed immediately with an update to 1 or 2 files on their end.  

I think the conversion pipeline elements are separate from the inference pipelines, and probably i2i is also separate from ControlNet, but just in case the line of code you modified gets used somehow for ControlNet, it is worth trying to check that this correction doesn't break something with ControlNet.  Both issues are/were about size inputs.

**Comment by vzsg** [comment]
A good point... it might also be used to feed controlnet. Unfortunately I don't have any more time today to go model hunting and experimenting, so if you can try it, that would be awesome.

Maybe CN is affected by the same bug and we'll just hit two birds with one stone 🙏🏻

**Comment by jrittvo** [comment]
Yes.  ControlNet at present works with a 768x512 set of models and a 512x768 input image.  So it is transposing h and w.  I will try next with your changed CGImage file in the pipeline and we'll see if it fixes ControlNet also.

**Comment by jrittvo** [comment]
Bingo!  Your fixed CGImage file also fixes ControlNet.  Now it works with the 2 models and the input image all set for the same size.  Pleasure doing business with you, Sir!

**Comment by jrittvo** [comment]
I just added a note to your PR to let them know that your fix has extra powers.

**Comment by vzsg** [comment]
Thanks. I also edited it in just before the comment :)

I hope they'll pick it up, along with that scheduler performance improvement that's approved but not merged yet.

**Comment by jrittvo** [comment]
They may be on Asian time.  I usually see change when I wake up in US Mountain.
