### ISSUE TITLE
I have problem when running on an intel based Mac

### ISSUE THREAD

**Issue by funland** [godly-devotion/MochiDiffusion#210]
### Running Latest Version

- [X] I am running the latest version

### Processor

Intel

### Intel processor

3.2 GHZ 6 core Intel Core i7

### Memory

16GB

### What happened?

While try every model , the feed back is always :
 Mochi Diffusion[20037:1053273] There was a problem generating images: Error Domain=com.apple.CoreML Code=0 "Error computing NN outputs." UserInfo={NSLocalizedDescription=Error computing NN outputs.}

Is there any setting I can adjust the NN feature and just supporting CPU & GPU ( or just CPU ) ?
I like the source code ,it 's elegant .
Thanks.
<img width="834" alt="截屏2023-03-30 10 38 43" src="https://user-images.githubusercontent.com/797076/228713997-34ee615f-efd4-42d9-a442-7b210d467c3a.png">

**Comment by kimobebe** [comment]
same problem here. Intel base MacBook .

**Comment by siriuscc** [comment]
me too,  support Intel?

**Comment by zhaozhining** [comment]
me too.
