### ISSUE TITLE
more Sampler please! 

### ISSUE THREAD

**Issue by wendaleruan** [godly-devotion/MochiDiffusion#212]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

We need more Sampler options 
such as DPM++ 2M Karras, DPM++ SDE Karras, etc.

### Why do you think this should be added?

Different Samplers different results!

**Comment by godly-devotion** [comment]
Mochi Diffusion is just a GUI to Apple's Stable Diffusion library. This will need to be implemented here: https://github.com/apple/ml-stable-diffusion
