### ISSUE TITLE
More improvements needed

### ISSUE THREAD

**Issue by jcplus** [godly-devotion/MochiDiffusion#215]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

- Allow more tokens in prompt
- Allow manually changing resolution
- Allow choosing sampling methods

### Why do you think this should be added?

- ControlNet
- Save/load/import presets of positive and negative prompts
- Lora
- Embeddings
- Hypernetworks
- Inpaint
- Outpaint
- Restore faces

**Comment by godly-devotion** [comment]
Mochi Diffusion is just a GUI to Apple's Stable Diffusion library. Most of these need to be implemented here: https://github.com/apple/ml-stable-diffusion
