### ISSUE TITLE
Having a problem while following Wiki's guidance to convert models

### ISSUE THREAD

**Issue by SGWinterlight** [godly-devotion/MochiDiffusion#217]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

8GB

### What happened?

I'm trying to turn a ckpt model into a CoreML one, everything went well, however when I'm trying to proceed the step of "SD model → Diffusers", I get a error like this:
<img width="1440" alt="Screenshot 2023-04-03 at 13 49 31" src="https://user-images.githubusercontent.com/69382696/229422317-61143262-e510-45d1-bea9-00cbb57cf3fe.png">
 Since I'm not familliar with anything aboutb Python, I'm not sure what to do about it. Could someone plz give me some tips?
(P.S. I'm not familiar with Github too, and I didn't find where to post questions about Wiki either, so if I posted this in the wrong place, please do notfiy me. Sorry for you inconvenience.)

**Comment by jettan** [comment]
I also ran into this while trying. It seems the script is a bit outdated and/or the diffusers python package has changed function names.

To fix this do the following:

In L21: change the function you want to import from `download_from_...` to `load_pipeline_from_...`
In L131 (where the function is used) also change the function call to the correct one you just fixed.

**Comment by SGWinterlight** [comment]
> I also ran into this while trying. It seems the script is a bit outdated and/or the diffusers python package has changed function names.
> 
> To fix this do the following:
> 
> In L21: change the function you want to import from `download_from_...` to `load_pipeline_from_...` In L131 (where the function is used) also change the function call to the correct one you just fixed.

Much appreciated. The script works after I applied your solution. However I encountered another problem, the outcome files I get after the whole process is Stable_Diffusion_version_nice_diffusers_vae_encoder.mlpackage and Stable_Diffusion_version_nice_diffusers_vae_decoder.mlpackage, that doesn't seemed to be working, did I messed up something again or it just should be like this?
Thanks for you patience again.

**Comment by jettan** [comment]
> > I also ran into this while trying. It seems the script is a bit outdated and/or the diffusers python package has changed function names.
> > To fix this do the following:
> > In L21: change the function you want to import from `download_from_...` to `load_pipeline_from_...` In L131 (where the function is used) also change the function call to the correct one you just fixed.
> 
> Much appreciated. The script works after I applied your solution. However I encountered another problem, the outcome files I get after the whole process is Stable_Diffusion_version_nice_diffusers_vae_encoder.mlpackage and Stable_Diffusion_version_nice_diffusers_vae_decoder.mlpackage, that doesn't seemed to be working, did I messed up something again or it just should be like this? Thanks for you patience again.

It means you're not done yet. in the wiki there are 2 parts of the conversion process. The first part is converting safetensors/ckpt weights to diffusers format (which you have now done I think. 
the next step is converting the diffusers format weights to coreml format (Step 2 in wiki).

https://github.com/godly-devotion/MochiDiffusion/wiki/How-to-convert-Stable-Diffusion-models-to-Core-ML#diffusers--mlmodelc

**Comment by jrittvo** [comment]
That first step should create a folder named "diffusers" with 1 file and 7 folders inside.  

That "diffusers" folder becomes the input to the second step.  

The second step also males a folder, this time with the model name you specified.  Inside this second folder are  4 files with names like the 2 you listed (Stable_Diffusion.......mlpackage) and a folder named "Resources".  The "Resources" folder is the final converted model. It has a .txt file, a .json file, and 4 .mlmodelc files.

What are you getting compared to all ths?

**Comment by jrittvo** [comment]
Sit tight for a bit.  I'm looking at the diffusers repo right now.  The script that gave you the initial error was changed from "download_from" to "load_pipeline_from" about 3 weeks ago.  At the same time, a line in src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py was changed in the same way.  That is the place where the function is defined.  It is the file in the miniconda env:  "coreml_stable_diffusion/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py".   I need to see if there were further changes to this file (that would have caused the mismatch error) and what else they may have changed.  You might just need to replace your current version of this file with another older version.  I'm in a bit over my head here, but let me look deeper.

Also, copy and paste in here the command you ran, exactly as it was entered, if possible, when you did that second step to convert from the diffusers folder.  All the --xxxxxx items are the names of the types of pieces you are telling it to make.  Maybe there is a typo somewhere that is causing it to not make some of the pieces.

**Comment by SGWinterlight** [comment]
> Ok. The current files in the diffusers repo use "def download_from_original_stable_diffusion_ckpt" which matches what was in your script before you changed "download_from" to "load_pipeline_from". So the script that downloads today does match the rest of the diffusers repo pieces that it comes from. But the conda env is not using the "convert_from_ckpt.py" file from the diffusers repo. It is using one it got through pip, when you ran "pip install -e ." That command tells pip to install a list of packages in "." which is a file named "requirements.txt". One of the packages listed in there is "diffusers[torch]". That could be from diffusers version 0.13.1 while the script from the diffusers repo is from diffusers version 0.14.0, and that mis-match could be part of the problem of the conversion not going through all the pieces. The pip repo could be behind the diffusers repo because they missed the update or because they are waiting to see if the update is good. The update to the diffusers repo was about 3 weeks ago.
> 
> But I'd like to eliminate the possibility of a typo in the command you entered first, since you seem to now have the script at least working part way with the diffusers package.

python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-decoder --convert-vae-encoder --convert-unet --convert-text-encoder --model-version nice_diffusers --bundle-resources-for-swift-cli --attention-implementation SPLIT_EINSUM -o nice_split-einsum
Honestly I just copy and paste it from Wiki. And my model is just named "nice".

**Comment by jrittvo** [comment]
Copy and pasting the command is the way to go.  That means the issue is either from the diffusers version mismatch or your machine is running out of resources and exiting in the middle of the process.  Can you paste in here the last bunch of lines that output to your terminal when the 2nd conversion appears to be done?  Say 20 lines worth?

**Comment by SGWinterlight** [comment]
> Copy and pasting the command is the way to go. That means the issue is either from the diffusers version mismatch or your machine is running out of resources and exiting in the middle of the process. Can you paste in here the last bunch of lines that output to your terminal when the 2nd conversion appears to be done? Say 20 lines worth?

<img width="1440" alt="Screenshot 2023-04-04 at 00 33 08" src="https://user-images.githubusercontent.com/69382696/229572812-5e0d1e96-8090-45f3-b54e-2ff6b254b24a.png">
I had tried multipled times and observed, every time the process will stuck at here, and either stop giving response or just exit.

**Comment by SGWinterlight** [comment]
holy shit. I just spotted that "killed python" in the middle of it. I supposed that means I ran out of memory. Mystery solved.

**Comment by jrittvo** [comment]
It could be that or a bad call caused you to run out of memory.  I'd like you to try an older version of the script, on that matches the diffusers package you have.  Rename the script you hae to .back and try with this script I'm attaching.
[convert_original_stable_diffusion_to_diffusers.zip](https://github.com/godly-devotion/MochiDiffusion/files/11140614/convert_original_stable_diffusion_to_diffusers.zip)

**Comment by jrittvo** [comment]
Let's see if the script change does anything.  And actually, even if it is a memory issue, which I think we can get around, you should be using a script that comes from the same version as the full diffusers package anyway.

**Comment by SGWinterlight** [comment]
> Let's see if the script change does anything. And actually, even if it is a memory issue, which I think we can get around, you should be using a script that comes from the same version as the full diffusers package anyway.

No luck. Ended in the same way. Maybe I'll try that solution of memory problem in the Wiki after I wake up hours later. Much appreciated to your concern and advice.

**Comment by jrittvo** [comment]
Was just going to suggest the wiki ideas, and I give you another option here in a bit that will be waiting for you to try when you get a chance.

**Comment by jrittvo** [comment]
I'd stick with the version of the script I sent anyway since it is the match to the version of diffusers you are using.

You can break the second conversion command into smaller steps which -may- reduce the peak memory load.  Try running these commands that do one conversion at a time and then bundles them with the last command.  If you watch the folder it is writing to, you'll notice at writes a file and then sometimes still does stuff to the file before giving you your terminal prompt back, so be patient.  If it fails because it can't complete, it will give you that "zsh killed python" message.

python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-decoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum

python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-encoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum

python -m python_coreml_stable_diffusion.torch2coreml --convert-unet --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum

python -m python_coreml_stable_diffusion.torch2coreml --convert-text-encoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum

python -m python_coreml_stable_diffusion.torch2coreml --model-version nice_diffusers --bundle-resources-for-swift-cli -o nice_split-einsum

If you get a full "Resources" folder in the end, remember that the first time in a session that you run any split-einsum model with "Use Neural Engine", it takes a few minutes for the model to load.

**Comment by SGWinterlight** [comment]
> I'd stick with the version of the script I sent anyway since it is the match to the version of diffusers you are using.
> 
> You can break the second conversion command into smaller steps which -may- reduce the peak memory load. Try running these commands that do one conversion at a time and then bundles them with the last command. If you watch the folder it is writing to, you'll notice it writes a file and then sometimes still does stuff to the file before giving you your terminal prompt back, so be patient. If it fails because it can't complete, it will give you that "zsh killed python" message.
> 
> python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-decoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum
> 
> python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-encoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum
> 
> python -m python_coreml_stable_diffusion.torch2coreml --convert-unet --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum
> 
> python -m python_coreml_stable_diffusion.torch2coreml --convert-text-encoder --model-version nice_diffusers --attention-implementation SPLIT_EINSUM -o nice_split-einsum
> 
> python -m python_coreml_stable_diffusion.torch2coreml --model-version nice_diffusers --bundle-resources-for-swift-cli -o nice_split-einsum
> 
> If you get a full "Resources" folder in the end, remember that the first time in a session that you run any split-einsum model with "Use Neural Engine", it takes a few minutes for the model to load.

SUCCESS! I'd like to express my sincerest gratitude to you, appreciated for your patience and valuable advice.

**Comment by jrittvo** [comment]
Happy to help and glad it worked in the end!

**Comment by stephen-liu-fipo** [comment]
For anyone encounterd this problem:

reason:  [the Python script](https://github.com/huggingface/diffusers/raw/main/scripts/convert_original_stable_diffusion_to_diffusers.py)  used in the Wiki is the latesd [diffuser](https://github.com/huggingface/diffusers) version (for me is 0.15.0.dev0).  But the installed diffuser is different(for me is v0.14.0), and `download_from_original_stable_diffusion_ckpt`  do not exist until https://github.com/huggingface/diffusers/commit/d761b58bfcd7213d61bbdb090f182694e17317c7# (version 0.15.0+).

You can solve this problem 

1: 
> I also ran into this while trying. It seems the script is a bit outdated and/or the diffusers python package has changed function names.
> 
> To fix this do the following:
> 
> In L21: change the function you want to import from `download_from_...` to `load_pipeline_from_...` In L131 (where the function is used) also change the function call to the correct one you just fixed.

2.
install the latest diffusers from github
