### ISSUE TITLE
Add image size option

### ISSUE THREAD

**Issue by xros** [godly-devotion/MochiDiffusion#218]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Add image size option when generating images

### Why do you think this should be added?

For example, portrait images

**Comment by vzsg** [comment]
CoreML models don't support variable sizes, the size they'll output is baked into them. So if you want to generate portraits, you should download an 512x768 model from HuggingFace, from the `original` subfolders. Keep in mind, that original models can only be executed with the GPU.
