### ISSUE TITLE
Problem generating image on Intel Mac

### ISSUE THREAD

**Issue by Jo6666887** [godly-devotion/MochiDiffusion#219]
### Running Latest Version

- [X] I am running the latest version

### Processor

Intel

### Intel processor

no matter what i say it always say"
There was a problem generating images: Error Domain=com.apple.CoreML Code=O "Error computing NN outputs."

Userlnfo=(NSLocalizedDescription=Error computing NN outputs.

### Memory

16GB

### What happened?

no matter what i say it always say"
There was a problem generating images: Error Domain=com.apple.CoreML Code=O "Error computing NN outputs."

Userlnfo=(NSLocalizedDescription=Error computing NN outputs.

**Comment by jrittvo** [comment]
What version of macOS are you running?  If it is before 13.0 I don't think it can work, and if it is the new 13.3 or a 13.4 beta, it is looking like Apple changed something that stops this from running on Intel processors.

**Comment by Jo6666887** [comment]
13.2.1 ,it should be fine? 😭

**Comment by Jo6666887** [comment]
this is my model 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/127669919/229631172-0d777a2a-33b7-4972-b297-c1437c5190dd.png">

**Comment by Jo6666887** [comment]
like this 
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/127669919/229631305-24cb4bef-9d20-4399-b0aa-c116d1fbfad1.png">

**Comment by jrittvo** [comment]
13.2.1 has worked ok for Intel for many people.  And your model looks ok.  Are you selecting "CPU & GPU" in the settings?

**Comment by withlin** [comment]
how to setting `CPU & GPU`?  @jrittvo

**Comment by jrittvo** [comment]
From the menu at the top of your screen, click on "Mochi Diffusion" and then "Settings.  When the little window opens, click on the little picture icon named "Image".  In the item "ML Compute Unit" part, set it to "CPU & GPU".  That is the choice for "original" type models, which is what you have in the screen cap you posted.  Hope it will work after that.

**Comment by withlin** [comment]
![image](https://user-images.githubusercontent.com/22409551/229676001-beeb8956-fc70-4b73-b839-e757be93f8be.png)
`In the item "ML Compute Unit" part, set it to "CPU & GPU". ` Not Found

![image](https://user-images.githubusercontent.com/22409551/229676090-344309e2-aae0-4f45-a123-1dbdc473de8a.png)

@jrittvo

**Comment by jrittvo** [comment]
Hmmmm.  Something is not right with the installation of Mochi on your machine.  I would delete it and download it fresh.  It is at version 3.1 now, but I don't think that is the problem.  Somehow your installation got corrupted, I think.
![Screenshot](https://user-images.githubusercontent.com/114269461/229677562-efcb6d33-322d-404e-9d0f-18565c9a9503.jpg)

**Comment by godly-devotion** [comment]
No that is correct, Intel Macs do not have the option for `ML Compute Unit` as it doesn't have Neural Engine.

**Comment by jrittvo** [comment]
He using an original model but it threw an error mentioning "NN".  I assumed that is "neural network".  Not the case?

**Comment by Galaxy955** [comment]
I met the same error in my Intel MacBook Air which is running macOS 13.3

**Comment by vzsg** [comment]
> He using an original model but it threw an error mentioning "NN". I assumed that is "neural network". Not the case? Or does neural network have nothing to do with neural engine?
> 
> There was a problem generating images: Error Domain=com.apple.CoreML Code=O "Error computing NN outputs."

Stable Diffusion uses neural networks to implement Unet and VAE.
That error, as cryptic as it is, has nothing to do with the Neural Engine.

**Comment by Jo6666887** [comment]
> ![image](https://user-images.githubusercontent.com/22409551/229676001-beeb8956-fc70-4b73-b839-e757be93f8be.png) `在项目 "ML计算单元 "部分，将其设置为 "CPU和GPU"。 ` 未找到
> 
> ![image](https://user-images.githubusercontent.com/22409551/229676090-344309e2-aae0-4f45-a123-1dbdc473de8a.png)
> 
> @jrittvo

My interface is exactly the same as yours, I downloaded the latest version, and did not find the author's screenshot of the option

**Comment by Jo6666887** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/127669919/229772085-c63b6c7a-df27-4175-9bd6-36ebb3b4a97c.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/127669919/229772157-4d3ecab9-3687-465d-9f6c-b55477d2901a.png">
same question

**Comment by 137943103** [comment]
我也遇到了同样的问题
