### ISSUE TITLE
Support macOS Monterey?

### ISSUE THREAD

**Issue by KengChiChang** [godly-devotion/MochiDiffusion#220]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Add support for macOS Monterey

### Why do you think this should be added?

Some people might choose to skip macOS Ventura since various small bugs reported, e.g., some discussions [here](https://www.reddit.com/r/MacOS/comments/10tljhe/upgrade_to_ventura_or_stay_on_monterey/).

**Comment by tanpaper** [comment]
Oh no, this is very sad, I need to upgrade my system, I can not guarantee that the software running on my current computer will still work on the new system
