### ISSUE TITLE
convert SD to diffusers failed

### ISSUE THREAD

**Issue by ifurme** [godly-devotion/MochiDiffusion#221]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

32GB

### What happened?

ImportError: cannot import name 'download_from_original_stable_diffusion_ckpt' from 'diffusers.pipelines.stable_diffusion.convert_from_ckpt'
(/opt/homebrew/Caskroom/miniconda/base/envs/coreml_stable_diffusion/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py)

can someone help me， i have tried many times，Whether it is the diffusers package of version 0.13.0 or 0.14.0

**Comment by ifurme** [comment]
https://github.com/godly-devotion/MochiDiffusion/issues/217

**Comment by disgaihsadkj** [comment]
怎么解决的

**Comment by jrittvo** [comment]
In file:  `convert_original_stable_diffusion_to_diffusers.py`

Line 21 change:  `download_from_`  to  `load_pipeline_from_`
Line 131 change:  `download_from_`  to  `load_pipeline_from_`
