### ISSUE TITLE
疑问：M1 Mac mini 下MochiDiffusion VS Stable-Diffusion-webui

### ISSUE THREAD

**Issue by 9Aiwan** [godly-devotion/MochiDiffusion#223]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

希望优化、功能添加如lora

设备：M1 Mac mini 16G
模型：V1.5
图像数量：1
迭代步数：20
关键词权重11.0

MochiDiffusion 耗时8分11秒，CPU平均95%+
stable-diffusion-webui 耗时3分50秒，CPU70%-95%浮动

疑问：按道理内置 [Apple 的 Core ML Stable Diffusion 框架]性能肯定要比WEB版强很多，目前体验效果很不理想，希望优化以及功能完善，期待

### Why do you think this should be added?

希望优化以及功能完善，期待

**Comment by vzsg** [comment]
8 minutes is definitely a lot for a single image. Which model were you using exactly?

**Comment by zhuHearthstone** [comment]
My computer is Apple M1 Pro 16G.It takes about 15 to 20 seconds per image.

**Comment by Jerry23011** [comment]
> MochiDiffusion 耗时8分11秒，CPU平均95%+

@9Aiwan Hi, 你确定使用了正确的模型和计算单元吗？CPU 的占用不应该这么高的，请仔细阅读 README 中的文档并按照操作试试，注意下载的模型和计算单元的选取

**Comment by crazyfish2020** [comment]
能不能加入像stable-diffusion-webui 加载一些需要的插件，入talker等
