### ISSUE TITLE
Always Loading the model...Maybe multi cores support needed

### ISSUE THREAD

**Issue by kingo233** [godly-devotion/MochiDiffusion#224]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

<img width="603" alt="截屏2023-04-06 16 38 39" src="https://user-images.githubusercontent.com/29831327/230322756-63b605d8-9842-43b7-90e0-6318225eef7f.png">

<img width="575" alt="截屏2023-04-06 16 39 21" src="https://user-images.githubusercontent.com/29831327/230322866-8f588e7e-c720-4d97-820b-eab0452159ec.png">

一核有难，七核围观
one core has problem,other seven cores just watching.

**Comment by vzsg** [comment]
That's part of a process that we have zero control over: the CoreML framework is loading the model files like that. Apple must've had a good reason to load models one-by-one, and for that loading to be single threaded. In either case, this is beyond Mochi and even ml-stable-diffusion. 🙁
