### ISSUE TITLE
Request to add LoRa functionality

### ISSUE THREAD

**Issue by li775176364** [godly-devotion/MochiDiffusion#225]
### Running Latest Version

- [x] I am running the latest version

### What do you want Mochi Diffusion to do?

Hopefully the next step will be to support the **LoRa**-class model

### Why do you think this should be added?

Which means MochiDiffusion moves from demonstration to productivity tool

**Comment by godly-devotion** [comment]
Mochi Diffusion is just a GUI to Apple's Stable Diffusion library. This will need to be implemented here: https://github.com/apple/ml-stable-diffusion

**Comment by li775176364** [comment]
### All right, anyway, thanks for your contribution !

**Comment by jrittvo** [comment]
This repo has some models converted to Core ML after a LoRA was merged into a base model.  Not the real thing, but a good bit of it . . .  

https://huggingface.co/jrrjrr/LoRA-Merged-CoreML-Models
