### ISSUE TITLE
[SD 2.1]: Black images are generated for `CPU & GPU` models that use “v_prediction"

### ISSUE THREAD

**Issue by manifestbound** [godly-devotion/MochiDiffusion#227]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

First, I’m genuinely thankful to the dev and the community for being able to try SD models with the help of the App & Wiki!

However, I noticed that Mochi Diffusion fails to work with models that are based on Stable Diffusion 2.1. 
- For `SPLIT_EINSUM` CoreML-generated models, the app’s spinner continuously spins and never (after waiting hours) finishes. 
- For some `CPU & GPU` CoreML generated models, the app does load the model but it produces images that are completely black; no images are generated. 

This behavior is consistent with a variety of SD-2.1 checkpoints -> models (per the instructions in the wiki). Here are some that I’ve confirmed to have issues with Mochi Diffusion (3.1):
- [Artius V2.1](https://civitai.com/models/27739/artius-v21)
- [rMada Merge - SD 2.1 768](https://civitai.com/models/15303/rmada-merge-sd-21-768)
- [Isometric Dreams SD2.1](https://civitai.com/models/8013/isometric-dreams-sd21) (Only `CPU & GPU` model works)

Strangely, both variants of the `stable-diffusion-2-base` work so I’m not sure if it's an issue with Mochi Diffusion, CoreML, or something else. I wanted to report this issue because this would heavily restrict users who want to use models beyond SD 1.x.

I am determined to run SD-2.1 based models and I would be more than happy to triage this issue together here and/or Discord.

---

System Info:
- Mac mini (M1, 2020)
- RAM: 16 GB
- macOS 13.3 (22E252)

**Comment by vzsg** [comment]
> Strangely, both variants of the stable-diffusion-2-base work so I’m not sure if it's an issue with Mochi Diffusion, CoreML, or something else. I wanted to report this issue because this would heavily restrict users who want to use models beyond SD 1.x.

I remember some discussion on Discord about the schedulers not supporting v-diffusion. For example, [this message](https://discord.com/channels/1068185566782423092/1068187870537449532/1075762505542029312) points to what's missing from ml-stable-diffusion. And I remember that someone already showed a patch to be applied on (Apple's) Swift code to achieve that formula, but can't find it now...

**Comment by manifestbound** [comment]
> I remember some discussion on Discord about the schedulers not supporting v-diffusion. For example, [this message](https://discord.com/channels/1068185566782423092/1068187870537449532/1075762505542029312) points to what's missing from ml-stable-diffusion. And I remember that someone already showed a patch to be applied on (Apple's) Swift code to achieve that formula, but can't find it now...

Interesting. What discord channel is the link pointing to? (Upon clicking the link it led me to a channel not found page)

And I can further confirm that switching from the builtin “DPM-Solver++” to the “PNDM” scheduler does not resolve this issues (for both `SPLIT_EINSUM` and `CPU & GPU` models).

**Comment by jrittvo** [comment]
Some of the clues to this riddle are in the `convert_original_stable_diffusion_to_diffusers.py` script.  Open it up as a text file and look at the various arguments it accepts.  There is one for loading the `yaml` file that pairs with SD 2.1 checkpoints, another for `epsilon` vs `v-prediction` prediction, and a handful more that are apparently needed for converting SD 2.1 checkpoints to diffusers.  I spent a day weeks ago trying various combinations of arguments and never seem to hit the jackpot.  There may also be tweaks needed to the commands that convert diffusers to coreml, but I suspect that meat of this is in the script noted above, because I have had some minor success converting SD 2.1 models that are already in diffusers format over to coreml models using the same commands that work for SD 1.5 models.

**Comment by manifestbound** [comment]
> Some of the clues to this riddle are in the `convert_original_stable_diffusion_to_diffusers.py` script. Open it up as a text file and look at the various arguments it accepts. There is one for loading the `yaml` file that pairs with SD 2.1 checkpoints, another for `epsilon` vs `v-prediction` prediction, and a handful more that are apparently needed for converting SD 2.1 checkpoints to diffusers. I spent a day weeks ago trying various combinations of arguments and never seem to hit the jackpot. There may also be tweaks needed to the commands that convert diffusers to coreml, but I suspect that meat of this is in the script noted above, because I have had some minor success converting SD 2.1 models that are already in diffusers format over to coreml models using the same commands that work for SD 1.5 models.

Glad to hear that others are hitting similar issues…

- If there’s more to set in the conversion scripts, then it would be swell for the [How to convert Stable Diffusion models to Core ML](https://github.com/godly-devotion/MochiDiffusion/wiki/How-to-convert-Stable-Diffusion-models-to-Core-ML) wiki to be updated to account for models with extra info.
- What makes this odd is that some models (see: [Isometric Dreams SD2.1](https://civitai.com/models/8013/isometric-dreams-sd21)) don’t have a custom YAML and it still causes the `SPLIT_EINSUM` models to infinitely attempt to load the model while its `CPU & GPU` variant works just fine...

**Comment by jrittvo** [comment]
The yaml file is just some configuration data that I think can be communicated to the pipelines in other ways, so it isn't just about that.  I'm sure the wiki will get updated as soon an someone figures out what the update needs to be, but it has been like 2 months and I don't think anyone has pinned down the right steps and arguments yet.  I do have an original 768x768 that I made from the SD-2.1-base diffusers set that I will add to the model repo later today.

**Comment by manifestbound** [comment]
> The yaml file is just some configuration data that I think can be communicated to the pipelines in other ways, so it isn't just about that. I'm sure the wiki will get updated as soon an someone figures out what the update needs to be, but it has been like 2 months and I don't think anyone has pinned down the right steps and arguments yet. I do have an original 768x768 that I made from the SD-2.1-base diffusers set that I will add to the model repo later today.

@jrittvo, do you by chance recall the command you used to generate your SD-2.1 model? (It could serve as a starting point for others)

**Comment by jrittvo** [comment]
I made that model starting from a git clone of the diffusers folders and model_index.json file from here (see screencap below):  https://huggingface.co/stabilityai/stable-diffusion-2-1-base/tree/main, not from a .ckpt or .safetensors file.  I put them in a folder named <model_name>/diffusers and proceeded with the Diffusers → MLMODELC step in the Wiki.  I don't think I used any special commands.  So I "cheated".  And what I did would only potentially work if you could find the diffusers version of a model.  Civitai doesn't ever have that, and HF sometimes doesn't either, as most people are using single file checkpoints in Automatic1111.

![Screenshot](https://user-images.githubusercontent.com/114269461/230797450-ea2f950c-ba2b-4872-8b5d-93709cd76764.jpg)

**Comment by jrittvo** [comment]
@あたたくん (atatakun) who is on the Mochi Discord server from time to time seems to have the best knowledge on converting SD 2.1 models.  He has gotten a few done and he has made the effort to really dig into documentation and git discussions to try to figure things out.

**Comment by manifestbound** [comment]
> @あたたくん (atatakun) who is on the Mochi Discord server from time to time seems to have the best knowledge on converting SD 2.1 models. He has gotten a few done and he has made the effort to really dig into documentation and git discussions to try to figure things out.

Thanks for pointing me to their discoveries. Thanks to them I now have an update (still broken but its one step at a time).
- On Discord, their observations with F16 models + GPU yielding black images is exactly what’s happening here. They mentioned applying two changes to the following files: `torch2coreml.py` and `DPMSolverMultistepScheduler.swift` to perhaps workaround with generating **FP32 Core ML** models on GPU.
- I applied the changes to the respective files and I used the following command to generate a `CPU & GPU` model:
```
python3 convert_original_stable_diffusion_to_diffusers.py --checkpoint_path artius-v2.1.safetensors --original_config_file artius-v2.1.yaml --from_safetensors --device cpu --scheduler_type dpm --image_size 768 --upcast_attention --prediction_type v_prediction --extract_ema --dump_path artius_v2.1_diffusers

python3 -m python_coreml_stable_diffusion.torch2coreml --compute-unit CPU_AND_GPU --convert-vae-decoder --convert-vae-encoder --convert-unet --convert-text-encoder --model-version artius_v2.1_diffusers --bundle-resources-for-swift-cli --attention-implementation ORIGINAL -o artius_v2.1_original
```
- And after generating and tossing it into Mochi Diffusion to generate an image, I get this…

![man standing in the middle of a city 2477527732](https://user-images.githubusercontent.com/130263290/230810513-45ba8b87-979d-4e63-96b9-552c79cca3db.png)

Definitely getting somewhere but it seems like any resulting image will come out to be a noisy mess.

---

- Also, their response kinda explains why one of the three models, [Isometric Dreams SD2.1](https://civitai.com/models/8013/isometric-dreams-sd21), was only able to be run on GPU with a `CPU & GPU` model.

**Comment by jrittvo** [comment]
I'd say that is serious progress.  It feels like it wants to calculate or whatever the term is at higher precision but I have no clue what controls that aspect.  Take good notes as you experiment and hopefully a pattern will emerge (excuse the pun) that moves you forward.

**Comment by manifestbound** [comment]
Another update, I realized that while I made changes to the `DPMSolverMultistepScheduler.swift` file when making a CoreML model… I didn’t incorporate the "v_prediction" workaround in Mochi Diffusion itself.

After cloning Mochi Diffusion and pointing to my modified local `ml-stable-diffusion` swift package, I generated one more image and…
![man standing in the middle of a city 2477527732](https://user-images.githubusercontent.com/130263290/230818291-97ba0c36-7a67-412b-9f04-453b77b70c89.png)

MUCH better. Image is still a little wonky so there’re still some lingering issues yet to be addressed. Also, getting here involved some changes, right now hacks, that definitely needs to be upstreamed into the [ml-stable-diffusion](https://github.com/apple/ml-stable-diffusion) swift package. Could someone, more technical than me, post the lack of `v_prediction` support as a **major** issue with models (like 2.1) going forward?

**Comment by jrittvo** [comment]
@godly-devotion posted a pull request at apple/ml-stable-diffusion to correct dimension arguments not being fully internalized and they merged it very quickly.  Maybe he can present this to them?  Can you share your code mods with him?

**Comment by manifestbound** [comment]
> @godly-devotion posted a pull request at apple/ml-stable-diffusion to correct dimension arguments not being fully internalized and they merged it very quickly. Maybe he can present this to them? Can you share your code mods with him? It would probably help point them to a fix . . .

Sure. Do note that whatever I’ve done isn’t the final solution but its a leap toward getting this addressed. I’ve attached the two files I’ve modified here with a clear `KINDA WORKAROUND FOR SD2.1` comment in each file.

[kinda_patches_issue227.zip](https://github.com/godly-devotion/MochiDiffusion/files/11187437/kinda_patches_issue227.zip)

**Comment by jrittvo** [comment]
Back to your initial post in this thread, the 2.1-base is a 512 model and the plain 2.1 is a 768.  Given the limit on split_einsum models of 512, I bet the solution past what you've achieved is a modification to ml-stable-diffusion itself both for v-prediction and the 768 size.

**Comment by jrittvo** [comment]
Thanks to atatakun and manifestbound, here is a collected methodology for converting SD-2.1 models and a suggested patch to the Mochi 3.1 code to build it so that it can run them:  https://huggingface.co/jrrjrr/Playground/blob/main/Converting%20%26%20Using%20SD-2.1%20Models.zip. 

There is also one already converted model at the is link:  https://huggingface.co/jrrjrr/Playground/blob/main/RE%20Meets%20WD%20Orig%20768.zip

This for tweakers to play with.  It isn't a practical solution yet because the modification to the Scheduler that enables SD-2.1 models cripples the use of SD-1.5 models.  Ultimately, this want to have an option toggle to go back and forth.

**Comment by vzsg** [comment]
One more case for forking ml-stable-diffusion and adding an option to select which algo to run.
(Then it could be attempted to get merged into the official version from there.)

**Comment by jrittvo** [comment]
This one would need some more poking around because the change is against a version of the scheduler from 0.2.0 (or whatever is in Mochi 3.1, that is why I used 3.1 to experiment).  But the line or two that get changed can probably be translated to what is in 1.0.0.  If I remember right, they changed the exact name of some of the variables involved.  Heck, maybe they even added in the alternate algorithm and it just needs the toggle added to the UI.

BTW, you just got feedback from ml-stable-diffusion.  Bet they merge your PR tomorrow.

**Comment by jrittvo** [comment]
While a lot of appreciated work went into investigating this issue, its was never resolved by Apple, it is kind of moot now that there are SDXL models.  I think this should be a closed issue.

**Comment by manifestbound** [comment]
Agreed. I myself have moved to using SDXL models. Thanks for the triaging everyone!
