### ISSUE TITLE
Why limit prompt words to 75 characters?

### ISSUE THREAD

**Issue by li775176364** [godly-devotion/MochiDiffusion#230]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Expand the capacity of prompt words, 

According to the experience summarized, generally **100~150** characters can satisfy most creations

### Why do you think this should be added?

75 characters is not enough in most cases

**Comment by vzsg** [comment]
The limit is not 75 characters but 75 tokens, counted by the BPE tokenizer. What your experience with A1111 was unfortunately doesn't apply here, the CoreML models are hard limited to 75 tokens and will simply ignore the extras.

**Comment by li775176364** [comment]
So, what happens if I use a prompt word longer than 75 characters?

Will it all participate in the calculation?

**Comment by vzsg** [comment]
No they won't. It will be as if you stopped typing when the counter hit 75.
