### ISSUE TITLE
Need CGF scale option

### ISSUE THREAD

**Issue by 13RTK** [godly-devotion/MochiDiffusion#231]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Need add the CGF scale option

### Why do you think this should be added?

The example images in civitai all have the CFG scale option, we need to follow these parameters
![image](https://user-images.githubusercontent.com/63441399/231689317-15417bb4-e278-4a84-870b-41ccf33ae2af.png)

**Comment by vzsg** [comment]
I have good news: the CFG scale option is already there.

![image](https://user-images.githubusercontent.com/1783465/231690094-546671a8-d312-465b-8ccb-0f5dc1de121c.png)

**Comment by 13RTK** [comment]
> I have good news: the CFG scale option is already there.
> 
> ![image](https://user-images.githubusercontent.com/1783465/231690094-546671a8-d312-465b-8ccb-0f5dc1de121c.png)

Thanks for your response! My problem was solved.
