### ISSUE TITLE
model requires these input features z: MultiArrary(Float16, 1 x 3 x 512 x 512)

### ISSUE THREAD

**Issue by Zhengquan** [godly-devotion/MochiDiffusion#234]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

32GB

### What happened?

text2image works properly, but errors are always reported when img2img. The size of the image is also 512 x 512, which conforms to the input format requirements

![image](https://user-images.githubusercontent.com/251222/232351301-092c3868-ba57-4822-90e7-bf8de9b1d062.png)

### Crash Log

```shell
no crash log
```

**Comment by jrittvo** [comment]
The version of the model you are using probably does not have a VAEEnvoder.mlmodelc bundle.  Without that, a model can do text2image but can not do image2image.

**Comment by Zhengquan** [comment]
> 



> The version of the model you are using probably does not have a VAEEncoder.mlmodelc bundle. Without that, a model can do text2image but can not do image2image.

here is the folder structure of the model, it has this bundle.

```bash
(coreml_stable_diffusion) ➜  lofi_V2_compiled $ tree .
.
├── TextEncoder.mlmodelc
│   ├── analytics
│   │   └── coremldata.bin
│   ├── coremldata.bin
│   ├── metadata.json
│   ├── model.mil
│   └── weights
│       └── weight.bin
├── Unet.mlmodelc
│   ├── analytics
│   │   └── coremldata.bin
│   ├── coremldata.bin
│   ├── metadata.json
│   ├── model.mil
│   └── weights
│       └── weight.bin
├── VAEDecoder.mlmodelc
│   ├── analytics
│   │   └── coremldata.bin
│   ├── coremldata.bin
│   ├── metadata.json
│   ├── model.mil
│   └── weights
│       └── weight.bin
├── VAEEncoder.mlmodelc
│   ├── analytics
│   │   └── coremldata.bin
│   ├── coremldata.bin
│   ├── metadata.json
│   ├── model.mil
│   └── weights
│       └── weight.bin
├── merges.txt
└── vocab.json

12 directories, 22 files
```

**Comment by jrittvo** [comment]
Could you possibly download and try the comparable model (`lofi-V2_original.zip` or `lofi-V2_split-einsum.zip`) from this location  https://huggingface.co/coreml/coreml-lofi-V2/tree/main  and see if it has the same problem with image2image?  It is working on my machine, and I tried the eplit_einsum one successfully with both CPU & GPU and CPU & Neural Engine.

![Screenshot](https://user-images.githubusercontent.com/114269461/232360122-ca73cb06-b301-43ec-ae47-1fffea63e0f2.jpg)
![Screenshot 1](https://user-images.githubusercontent.com/114269461/232360332-bbcc4a09-c3fb-4999-9c25-25cad928d7e9.jpg)

**Comment by Zhengquan** [comment]
> Could you possibly download and try the comparable model (`lofi-V2_original.zip` or `lofi-V2_split-einsum.zip`) from this location https://huggingface.co/coreml/coreml-lofi-V2/tree/main and see if it has the same problem with image2image? It is working on my machine, and I tried the eplit_einsum one successfully with both CPU & GPU and CPU & Neural Engine.


it works for lofi-V2_original.zip, seems my environment issues.

**Comment by jrittvo** [comment]
All of the models at the repo I linked to above were converted by people who use them for Mochi Diffusion.  There are 80 models there presently, and if there is one you would like that is not there, add a message to this thread anytime and I'd be happy to convert it and upload it for you.  There are issues with converting some SD-2.1 based models, but anything based on SD-1.5 models should be no problem.
