### ISSUE TITLE
Cannot find a file in converting process

### ISSUE THREAD

**Issue by breadjuice** [godly-devotion/MochiDiffusion#236]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

8GB

### What happened?

<img width="652" alt="image" src="https://user-images.githubusercontent.com/30001126/233452874-ddea8bf9-fe88-4633-abeb-8ad0b49c5622.png">
No matter i convert the diffusers in split-einsum or Origin way, this FileNotFoundError appears, why and how should i solve it?

**Comment by godly-devotion** [comment]
As this is more of a question than a bug, please ask on the [project Discord channel](https://discord.gg/x2kartzxGv).

**Comment by magnu5** [comment]
There is an error in the documentation on https://github.com/godly-devotion/MochiDiffusion/wiki/How-to-convert-Stable-Diffusion-models-to-Core-ML.
Step 3. i. has an extra tickmark at the end:
`python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-decoder --convert-vae-encoder --convert-unet --convert-text-encoder --model-version <MODEL-NAME>_diffusers --bundle-resources-for-swift-cli --attention-implementation SPLIT_EINSUM -o <MODEL-NAME>_split-einsum` `

compilation succeeds when that is removed as so:

`python -m python_coreml_stable_diffusion.torch2coreml --convert-vae-decoder --convert-vae-encoder --convert-unet --convert-text-encoder --model-version <MODEL-NAME>_diffusers --bundle-resources-for-swift-cli --attention-implementation SPLIT_EINSUM -o <MODEL-NAME>_split-einsum`

**Comment by godly-devotion** [comment]
@magnu5 Nice catch, fixed. The wiki is available for anyone to edit so if you happen to find other issues please feel free to fix it.
