### ISSUE TITLE
macOS Monterey can't use v3.2 of the Mochi Diffusion

### ISSUE THREAD

**Issue by yanghuaitao** [godly-devotion/MochiDiffusion#250]
### Running Latest Version

- [X] I am running the latest version

### Processor

Intel

### Intel processor

MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) 
Processor 2.9 GHz Dual-Core Intel Core i5
Memory 16GB

### Memory

16GB

### What happened?

I can't use the version of the application "Mochi Diffusion" with this version of macOS as soon as I finished to download the dmg file.

**Comment by vzsg** [comment]
That's normal, since Mochi (or rather, the underlying ml-stable-diffusion package) relies on a new version of CoreML, introduced in macOS Ventura 13.1.

**Comment by jrittvo** [comment]
Apple builds the OS and the CoreML pipeline.  Mochi and other implementations of CoreML are bound to what Apple provides.  The latest CoreML components and tools from Apple that are used in Mochi 3.2 have dropped support for Intel CPUs.  There is not much Mochi can do about this.  Intel chips probably see more support in a plain python-diffusers system, but you lose the speed and memory optimizations in CoreML for the M1/M2 and the integrated graphics/neural engine.  It's a shame, but that's the reality.

**Comment by yanghuaitao** [comment]
Is there any available version of Mochi Diffusion for my laptop?

**Comment by vzsg** [comment]
No, Ventura 13.1 has been a minimum from the very beginning.

**Comment by yanghuaitao** [comment]
So I have to update my laptop, LOL.....
