### ISSUE TITLE
Queue generation of multiple prompts

### ISSUE THREAD

**Issue by Naoray** [godly-devotion/MochiDiffusion#251]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Being able to start multiple different prompt generations at once

### Why do you think this should be added?

Generating images from prompts takes a little while. Being able to start multiple different prompts at once would make it possible to leave the prompt generation happen while the user doesn’t have to wait in front of the pc until the first prompt generation is ready to insert a new one.

**Comment by atemiz** [comment]
I think we need a queue feature in general.
Later, shortcuts that fill the queue with multiple prompt, step, guidance or seed values can be added for automation.
