### ISSUE TITLE
Support for additional aspect ratios and resolutions

### ISSUE THREAD

**Issue by iloving** [godly-devotion/MochiDiffusion#252]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Options to adjust the aspect ratios (4:3, 16/9) and/or resolutions (4k, 8k, user defined?) of the images generated or upscaled.

### Why do you think this should be added?

This would be helpful for people who want to, say, use an image as a wallpaper that matches the dimensions of their monitor, or maybe laser engrave or something.

**Comment by vzsg** [comment]
CoreML models don't support variable resolutions, that goes for both the generational and the upscaling models. Until/if that becomes a possibility, you can download differently sized variations of most generational models from HuggingFace.

**Comment by godly-devotion** [comment]
Duplicate of #148.
