### ISSUE TITLE
Is token counting working correct?

### ISSUE THREAD

**Issue by linanzi** [godly-devotion/MochiDiffusion#254]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

16GB

### What happened?

It said prompt "Emma Watson as a powerful mysterious sorceress, casting lightning magic, detailed clothing, digital painting, hyperrealistic, fantasy, Surrealist, full body, by Stanley Artgerm Lau and Alphonse Mucha, artstation, highly detailed, sharp focus, sci-fi, stunningly beautiful, dystopian, iridescent gold, cinematic lighting, dark" is 79 tokens.

**Comment by vzsg** [comment]
If it said that this prompt is 79 tokens, then it **is** 79 tokens. The counter works by running the exact same BPE tokenizer that the stable diffusion pipeline uses to feed your prompt into the process.
