### ISSUE TITLE
where can I get ControlledUnet.mlmodelc?

### ISSUE THREAD

**Issue by crazyshitass** [godly-devotion/MochiDiffusion#262]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

As mentioned here https://huggingface.co/jrrjrr/CoreML-Models-For-ControlNet/discussions/2
"Does your Mochi not "see" and list the different ControlNet modules that you put in your controlnet folder when you try to use a ControlNet?Are you using one of the ControlNet capable base models from this repo when you try to use ControlNet? (Your base model needs to have a ControlledUnet.mlmodelc in it, not just a Unet.mlmodelc.)"
No idea where to get "ControlledUnet.mlmodelc"

**Comment by jrittvo** [comment]
They get created when certain settings are used for converting a model to CoreML format.  There are 6 different already converted models that all have a ControlledUnet.mlmodelc in them in that repo you saw the comment at.  Here is a direct link to those converted base models:

https://huggingface.co/jrrjrr/CoreML-Models-For-ControlNet/tree/main/SD

To get a ControlledUnet.mlmodelc for other models, they will need to be converted using the instructions at:

https://huggingface.co/jrrjrr/CoreML-Models-For-ControlNet
and
https://huggingface.co/jrrjrr/CoreML-Models-For-ControlNet/tree/main/MISC

Setting up to do conversions yourself is quite a bit of work . . .
