### ISSUE TITLE
Larger image sizes

### ISSUE THREAD

**Issue by calben99** [godly-devotion/MochiDiffusion#265]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

It would be nice to be able to generate larger images, either with custom image sizes, or with Latent upscale.

### Why do you think this should be added?

In my testing with stable diffusion, Latent upscale using DPM++ SDE Karras gives a much cleaner large image versus the current implementation for upscaling in Mochi Diffusion.

**Comment by jrittvo** [comment]
An alternate upscaller using BSRGAN is in the works. That effort may also open to door to additional options.  Stay tuned . . .
