### ISSUE TITLE
Make img2img image well an image well

### ISSUE THREAD

**Issue by jmilr** [godly-devotion/MochiDiffusion#267]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I find myself dragging images into the img2img image well without thinking, and it does nothing

### Why do you think this should be added?

I just noticed it works for the control net well - is there a reason img2img can't be dragged into or clicked? Also saves having a dedicated button to add the image since you can just click a well.

![image](https://github.com/godly-devotion/MochiDiffusion/assets/15384770/6fd9f7ac-31c7-46eb-ab84-4baa5aee288b)

**Comment by jrittvo** [comment]
I think this they way to go, if the empty well can display something like

Drop Starting Image
           HERE
  Or click to browse
      to an image

And the title could change to IMAGE2IMAGE.  

The CONTROLNET could be set up exactly the same, with the drop-down in place of the slider.
Simplifies everything visually, and you get a largr space for the image to display.

**Comment by jmilr** [comment]
@jrittvo Yep, sounds perfect 👌 I'd only worry reducing the sidebar much more would make the prompt inputs annoying to work with, but I'm sure there's sweet-spot or a rejig of the layout.

**Comment by jrittvo** [comment]
The user can resize the sidebar, above a minimum width.  The code sets the minimum width, so that could be locked in to something that makes sense for the prompt boxes, if it isn't already set that way.

**Comment by jrittvo** [comment]
I realized that there is an issue with making the image wells wider.  They also get taller.  This increases the length of the sidebar column.  It will probably need scrolling, or it will need more scrolling, depending on your main window size.  I personally dislike having to scroll.  I much prefer being able to see and access everything at once, even if that means things are smaller.
