### ISSUE TITLE
keyword weight

### ISSUE THREAD

**Issue by alex-enchi** [godly-devotion/MochiDiffusion#281]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

I am using `stable-diffusion-v2.1-base_original_compiled` and tested prompt from [one of the tutorials](https://stable-diffusion-art.com/prompt-guide/#Keyword_weight)

> Oil painting portrait of [Joe Biden: Donald Trump: 0.9]

with
```
steps: 30
guidance scale: 7
seed: 3456720938
```
and no matter which ration 0....9 I am using I am getting the same output
Unfortunately I could not find anything related to keyword weights and is MochiDiffusion does anything additional with prompt.

So the question is does weights work and what is the syntax?

Thank you.

![Oil painting portrait of  Joe Biden: Donald Trump: 0 9 294 3456720938](https://github.com/godly-devotion/MochiDiffusion/assets/24417201/20a7575b-1d28-41ce-af74-564875551b8d)

**Comment by jrittvo** [comment]
The underlying code (from Apple's Core ML packages) doesn't support prompt weighting, and Mochi tries not to deviate from these base packages.  There have been several new code additions over at apple/ml-stable-diffusion in the past 2 months that added features found in Python-Diffusers implementations, so there is always a possibility that prompt weighting will be added to Core ML by Apple, and then Mochi will be able to add the feature also.

**Comment by alex-enchi** [comment]
Got it
Thank you!
