### ISSUE TITLE
Build Error: Type 'NSImage' does not conform to protocol 'Transferable'

### ISSUE THREAD

**Issue by simd-float4x4** [godly-devotion/MochiDiffusion#290]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

8GB

### What happened?

Build Error **Type 'NSImage' does not conform to protocol 'Transferable'** occurs at line:54 of Extensions.swift 
Does anyone have an idea how to rewrite the code or solve the problem?

**Extensions.swift line:54**
--------------------------------
extension NSImage: Transferable { 　_**//Error: Type 'NSImage' does not conform to protocol 'Transferable'**_
    private static var urlCache = [Int: URL]()

    public static var transferRepresentation: some TransferRepresentation {
        // swiftlint:disable:next trailing_closure
        ProxyRepresentation<NSImage, URL>(exporting: { image in
            let nsImage: NSImage = image
            return try nsImage.temporaryFileURL()
        })
    }
-------------------------------

**Comment by simd-float4x4** [comment]
XCode version: Version 15.0 beta 2 (15A5161b)

**Comment by jrittvo** [comment]
Meaning just edit the first linet to this?

 extension NSImage: {

**Comment by ZachNagengast** [comment]
Yep exactly

**Comment by simd-float4x4** [comment]
Thank you for answer!
I'll try it later, and if there were some problem, I'll give you a question again.
