### ISSUE TITLE
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path_or_dict'

### ISSUE THREAD

**Issue by leebeet** [godly-devotion/MochiDiffusion#313]
### Processor

M1 (or later)

### Memory

8GB

### What happened?

when i tried to run the convert_original_stable_diffusion_to_diffusers.py, the terminal stops and return this:
File "/Users/libotong/convert_original_stable_diffusion_to_diffusers.py", line 155, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path_or_dict'

it looks like the args in this method is not right anymore? maybe diffusers lib has been updated this api. i dont, now the converting is not working here.

**Comment by jrittvo** [comment]
The script is from the Hugging Face Diffusers repo at https://github.com/huggingface/diffusers. The diffusers package has been updated a few times recently, as have several other packages used in the model conversion pipelines.  Open an issue at that repo and perhaps they can get you going.

We can also try to help you over at the Mochi Discord server's model conversion issues channel: https://discord.gg/x2kartzxGv and https://discord.com/channels/1068185566782423092/1147197089298792548 if you post the full conversion command that you are trying to use over there.  Also, give a look at this post: https://github.com/godly-devotion/MochiDiffusion/issues/310.

**Comment by jrittvo** [comment]
I collected stuff from my miniconda environment for doing models conversions at this link, if you want to try the packages/scripts that have been working for me:

https://huggingface.co/jrrjrr/Playground

**Comment by jiangdi0924** [comment]
got the same issue ..

**Comment by jrittvo** [comment]
> got the same issue .. ( old version is fine.)

Please leave a bug report at the diffusers repo.

**Comment by godly-devotion** [comment]
As @jrittvo, unfortunately theres nothing we can do on our side.
