### ISSUE TITLE
Sorting logic for output files seems broken

### ISSUE THREAD

**Issue by jw-12138** [godly-devotion/MochiDiffusion#314]
### Processor

M1 (or later)

### Memory

16GB

### What happened?

Sorting for files revert back to `oldest first` when the textarea is focused, i believe this is a bug.

https://github.com/godly-devotion/MochiDiffusion/assets/29943110/8d3bf21f-c2f2-4e09-96fb-dfa8562a3503

<img width="827" alt="image" src="https://github.com/godly-devotion/MochiDiffusion/assets/29943110/7106b945-ddb8-417e-9326-dccae7b316f5">

<img width="396" alt="image" src="https://github.com/godly-devotion/MochiDiffusion/assets/29943110/2bcdde1a-7fdd-48e5-8199-736d923cd77d">

**Comment by Zae** [comment]
having the same problem after updating to sonoma.

**Comment by jrittvo** [comment]
I'm pasting in a screen cap of the warnings I get when I build Mochi for macOS 14.  Any chance that the highlighted warning is related to the reordering behavior? 
![Screencap](https://github.com/godly-devotion/MochiDiffusion/assets/114269461/7bb40a3d-1d3c-4ce8-96e2-d50b95c5175e)

**Comment by vzsg** [comment]
Unfortunately no, I fixed that warning in one of my attempts and it made no difference. You can also delete the whole `onChange` modifier to test it quicker.

I also went full lumberjack on the gallery and deleted a _lot_ of code, to the point that I was actively deleting all functionality from the view apart from displaying images, and the issue still remained.

**Comment by jrittvo** [comment]
It is a very weird issue. When it was first reported, a month or two ago, it was happening for some people and not for others. As if the bug was in the OS (13.x vs  13.y) and not the app itself.  And for a while it seemed it was fixed, and then it returned.  I guess it is too involved to put on StackExchange for ideas . . .

**Comment by jw-12138** [comment]
can confirm this fixed in version 4.7!
