### ISSUE TITLE
FreeU/Free Lunch

### ISSUE THREAD

**Issue by christopher-altman** [godly-devotion/MochiDiffusion#317]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

Will you be incorporating the [FreeU/Free Lunch unet patch fix](https://github.com/WASasquatch/FreeU_Advanced) in the next distribution?

### Why do you think this should be added?

It’s free! No computational cost whatsoever. Dramatically improves results.

**Comment by vzsg** [comment]
My two cents: patching the UNet model at runtime isn't really an option with CoreML models after they are converted. I assume this FreeU is similar to LoRAs, and would also have to be applied before model conversion.

**Comment by godly-devotion** [comment]
This is something that needs to be implemented in Core ML, nothing Mochi can do right now.
