### ISSUE TITLE
coreml-stable-diffusion-xl-base-ios

### ISSUE THREAD

**Issue by alex-enchi** [godly-devotion/MochiDiffusion#319]
### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

I am not sure is it bug or not, but that model is not visible in the model list
https://huggingface.co/apple/coreml-stable-diffusion-xl-base-ios

Is it possible to use "ios" models with mochi?

**Comment by vzsg** [comment]
It's not a bug, more like a missing feature. The repo has chunked UNet (to better fit iOS devices), which Mochi does not support at the moment – it expects UNet to be a single piece. But I think that should be an easy fix.

**Comment by vzsg** [comment]
Well, detection was easy to fix locally, but the model crashes ml-stable-diffusion. 😟 

```
{NSLocalizedDescription=/Users/zsolt/MochiDiffusion/models/coreml-stable-diffusion-xl-base-ios_split_einsum_compiled/UnetChunk1.mlmodelc/coremldata.bin is not a valid .mlmodelc file because the first word (1936876918) is not recognizable. : unspecified iostream_category error}
```

I'm not sure what's going on.

**Comment by ZachNagengast** [comment]
I just tried this out and the ios model runs fine on macOS 14 with @vzsg's model detection change. What OS version are you on?

**Comment by godly-devotion** [comment]
I'm thinking of raising the minimum version to macOS 14.1 once its released. There's been a lot of improvements to Core ML in Sonoma, and we wouldn't need to check XL support. All Apple Silicon devices support Sonoma as well.

**Comment by vzsg** [comment]
> I just tried this out and the ios model runs fine on macOS 14 with @vzsg's model detection change. What OS version are you on?

14.0 (23A344). What version are you on?

I'll also try redownloading the model, maybe it got messed up somehow.

**Comment by vzsg** [comment]
Actually, the files were truncated on my machine. I must've made a mistake.
Anyhow, after redownloading the zip, it works :)
