### ISSUE TITLE
The full screen will be restored after setting the priority display order of the images.

### ISSUE THREAD

**Issue by shenyx110** [godly-devotion/MochiDiffusion#326]
### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

The full screen will be restored after setting the priority display order of the images.

**Comment by vzsg** [comment]
I believe this is a duplicate of #314, or at least caused by the same underlying issue, where changing any property of the singletons trigger multiple changes in the complete SwiftUI universe. I don't see the light at the end of the tunnel yet.

**Comment by jrittvo** [comment]
https://github.com/godly-devotion/MochiDiffusion/issues/314#issuecomment-1771894885
