### ISSUE TITLE
Infinite loading model

### ISSUE THREAD

**Issue by misteral** [godly-devotion/MochiDiffusion#331]
### Processor

M1 Pro (or later)

### Memory

16GB

### What happened?

Infinite loading model

Mochi Diffusion: Version 4.4
MacOS: 13.6
Model: [crystalClearXL _original_SDXL_8-bit](https://huggingface.co/coreml-community/coreml-crystalClearXL_SDXL_8-bit)

Screenshot: 
![Screenshot 2023-10-23 at 18 51 35](https://github.com/godly-devotion/MochiDiffusion/assets/716630/44dea250-7e8b-4ce6-8e34-f053ffff549f)

**Comment by jrittvo** [comment]
SDXL models in Mochi likely need macOS 14 to be able to run.

**Comment by godly-devotion** [comment]
As @jrittvo mentioned, SDXL models require macOS 14 to run.

**Comment by misteral** [comment]
Oh ok, thanks guys!
