### ISSUE TITLE
How to use the SDXL Turbo Model?

### ISSUE THREAD

**Issue by RageshAntonyHM** [godly-devotion/MochiDiffusion#348]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

There is a new model released named SDXL Turbo. It is a faster model with 1-4 step generation. How to use this?

### Why do you think this should be added?

People can utilise this faster model

**Comment by Draxredd** [comment]
Sadly Mochi lowest step setting is 2, which spoils  SDXL turbo results.

**Comment by RageshAntonyHM** [comment]
@Draxredd 
But TurboXL performs good till 4 steps. So 2 won't be a problem

**Comment by godly-devotion** [comment]
SDXL Turbo needs a turbo-specific noise scheduler and an Euler ancestral sampler to work, neither is available at the moment with ml-stable-diffusion.

**Comment by RageshAntonyHM** [comment]
@godly-devotion 

Well, I see. Thanks

So we need to wait for apple to implement this!.
