### ISSUE TITLE
Send app notification when image generation is done

### ISSUE THREAD

**Issue by mangoes-dev** [godly-devotion/MochiDiffusion#350]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

I'd like there to be a Notification Centre popup when the queue is empty (i.e. all the images I queued have now been generated). Should only trigger if the app is not in foreground.

We can make this configurable and opt-in - for example only send the notification if there's been 5 or more images queued or base it on the time taken since the app was last in the foreground.

### Why do you think this should be added?

My workflow typically involves queueing up a bunch of images, then doing unrelated things on my computer until they're done. Having a notification would be awesome so I know when the images are done.

Should be do-able to do local notifications using [UNUserNotificationCenter](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) - no servers involved.

**Comment by mangoes-dev** [comment]
FWIW I'd be happy to have a go at implementing this - if you think this feature is worth having and nobody else is working on it :)

**Comment by godly-devotion** [comment]
> FWIW I'd be happy to have a go at implementing this - if you think this feature is worth having and nobody else is working on it :)

Go for it 👍
