### ISSUE TITLE
Add abbility to set percise Guidance Score between 0 and 1 for SDXL Turbo

### ISSUE THREAD

**Issue by FlipTip** [godly-devotion/MochiDiffusion#373]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

it should at least be possible to set the guidance score between 0 and 1 by entering a number, preferably with a slider for SDXL-Turbo models

## Text-to-image:

> "SDXL-Turbo does not make use of guidance_scale or negative_prompt, we disable it with guidance_scale=0.0. Preferably, the model generates images of size 512x512 but higher image sizes work as well. A single step is enough to generate high quality images." ([huggingface.co/stabilityai/sdxl-turbo](https://huggingface.co/stabilityai/sdxl-turbo))

A Guidance Score of 1 leads to oversaturated, unclear and ugly pictures like this, getting increasingly worse with more steps: 

![image](https://github.com/godly-devotion/MochiDiffusion/assets/80885397/f783092c-e76e-4ce6-8b23-f0432d67ebc7)

**Comment by godly-devotion** [comment]
SDXL Turbo is not supported yet. See #348.
