### ISSUE TITLE
loading pipeline error when generate image 

### ISSUE THREAD

**Issue by cxyfreedom** [godly-devotion/MochiDiffusion#375]
### Processor

M1 (or later)

### Memory

16GB

### What happened?

OS: 13.5 (22G74)

when click generate button, the main view toast "There was a problem loading pipeline."

<img width="1371" alt="image" src="https://github.com/godly-devotion/MochiDiffusion/assets/8132652/a125ba70-3c60-4c4f-9ccf-5efcbc156194">

**Comment by vzsg** [comment]
You need to be running Sonoma (preferably the latest 14.2.1) to be able to run SDXL models.

**Comment by cxyfreedom** [comment]
> You need to be running Sonoma (preferably the latest 14.2.1) to be able to run SDXL models.

The README.md write "Compatibility: macOS Ventura 13.1 and later"

**Comment by vzsg** [comment]
There's no contradiction. The app works on Ventura and you can run SD models with it.
But SDXL needs the new version of CoreML that Apple shipped with Sonoma.

**Comment by cxyfreedom** [comment]
> There's no contradiction. The app works on Ventura and you can run regular SD models with it. But SDXL needs the new version of CoreML that Apple shipped with Sonoma.
> 
> Though I guess the README could be more clear about this.

Yes, It works on the SD models. Tks
