### ISSUE TITLE
When will training be added?

### ISSUE THREAD

**Issue by midescribba** [godly-devotion/MochiDiffusion#381]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

When will training be implemented since on Automatic1111 it keeps crashing when I try to train a model. Thanks!

### Why do you think this should be added?

Training is slow on Macs and would be great if there was mps acceleration.

**Comment by vzsg** [comment]
MochiDiffusion is a frontend for Apple's [ml-stable-diffusion](https://github.com/apple/ml-stable-diffusion), so a feature request that deep would be in a better place there, if at all feasible.
