### ISSUE TITLE
[Bug]: No models found under model directory

### ISSUE THREAD

**Issue by jackhagley** [godly-devotion/MochiDiffusion#90]
### Running Latest Version

- [X] I am running the latest version

### Processor

M1 (or later)

### Memory

64GB (or higher)

### What happened?

Can’t set the model directory

It keeps adding /MochiDiffusion/models to whichever folder I choose

Doesn’t work with symlinks or with actual files

**Comment by basvdijk** [comment]
Did you put the models in subdirectories? So the structure is like:
```
Mochi Diffusion
 |_ models
     |_ stable-diffusion-v1-5_original_compiled
          |_ merges.txt
          |_ SafetyChecker.mlmodelc
          |_ TextEncoder.mlmodelc
          |_ Unet.mlmodelc
          |_ UnetChunk1.mlmodelc
          |_ UnetChunk2.mlmodelc
          |_ VAEDecoder.mlmodelc
          |_ vocab.json
```
