### ISSUE TITLE
[Feat]: Please add an option to use the safety checker.

### ISSUE THREAD

**Issue by whosawhatsis** [godly-devotion/MochiDiffusion#93]
### Running Latest Version

- [X] I am running the latest version

### What do you want Mochi Diffusion to do?

As the title, an option to use the safety checker would be useful. Maybe even offer an alternate download that has it permanently-enabled, so that it's not easy for users to turn it off.

### Why do you think this should be added?

My primary use case is to allow kids to play with image generation, while making it as unlikely as possible that they'll get nsfw results. Of course, another use case would be workplaces, where you literally need to keep it safe-for-work.

**Comment by marcomastri** [comment]
A workplace/document functionality would be great indeed, so that a user could save different documents with different prompts, templates, generation settings... and keep track of the generated images without having to delete them when he wants to start with a new project. 

Saving these documents would also make it possible not to lose the generated images each time the application is started.

**Comment by godly-devotion** [comment]
I've added the option to Filter Inappropriate Images under Settings. However do note that in my limited testing with the Core ML Stable Diffusion v1.5 model, it did not work. I'm not sure if that is a problem with Apple's library that I am calling or the model's safety checker module is not working properly. So I would first test the filter with different models to see which ones work correctly. You can tell if a model provides the safety checker if there is a file named `SafetyChecker.mlmodelc`.

**Comment by whosawhatsis** [comment]
I haven't tried it with the coreml files, but I have successfully change the VAE in a diffusers-format model (also a folder with separate files) by simply switching out the .bin file in the VAE folder. If the same works for the coreml conversions, adding a the safety checker to a model that doesn't include it should be as simple as copying the file over from one that does. It's not like the models are all training their own safety checkers...

Btw, using a converted version of vae-ft-mse-840000-ema would be a simple way to get a significant quality improvement on most models. I'll see if I can work out how to convert that to coreml.

**Comment by whosawhatsis** [comment]
In fact, you can probably convert it once and just symlink it into each model folder.

**Comment by whosawhatsis** [comment]
Yeah, not working at all. Looking at the commit, I see you added code to run the safety checker, but I don't see anything that actually does anything different with images that it flags as nsfw. I think all the safety checker does is tell you whether nsfw content has been detected, then you still need to blur it, or return an empty image, or something. I think the safety checker also requires the feature extractor, so we'll have to figure out how to convert that tool.
